name: Generate and Upload SBOM

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # syftでSBOMファイルを生成する
      - name: Generate SBOM with syft
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom.spdx.json

      # 生成したSBOMをDependency graphに送信
      - name: Submit SBOM to dependency graph
        uses: advanced-security/spdx-dependency-submission-action@v0.1.0
        with:
          filePath: "."
          filePattern: "*.spdx.json"

      # ArtifactsとしてSBOMを保存
      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: sbom.spdx.json
          retention-days: 90
